In [1]:
import numpy as np

In [2]:
stages = 3
start_times = [2, 4, 5, 6]
times = [2, 4, 3, 1]

#start_times = [2, 3, 4, 5]
#times = [4, 3, 2, 1]

In [3]:
# create a zero array to represent all open times

matrix = np.zeros((len(start_times),12))

matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
# loop thru the start times and create vectors that span the hours each band will play for.
# each band is on a separate record
# if a band is playing in a given hour the value is assigned a 1, it remains zero if they are not playing.

for start in start_times:
    idx = start_times.index(start)
    hours = times[idx] + 1 + start
    matrix[idx, start:hours] = 1
matrix

array([[0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.]])

In [5]:
# sum each column and create an array of the sums. The sum represnts the number of bands playing in each given hour.

sums = matrix.sum(axis=0)
sums

array([0., 0., 1., 1., 2., 2., 3., 3., 2., 0., 0., 0.])

In [6]:
# if the number of bands playing in each given hour is less than or equal to the number of stages, the test passes.
# Otherwise it fails.

for i in sums:
    if i > stages:
        answer = "false"
        break
    else:
        answer = "true"
        next
        
    
print(answer)

true
