In [1]:
import numpy as np

In [24]:
stages = 3
start_times = [2, 4, 5, 6]
times = [2, 4, 3, 1]

#start_times = [2, 3, 4, 5]
#times = [4, 3, 2, 1]

In [25]:
matrix = np.zeros((len(start_times),12))

matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
for start in start_times:
    idx = start_times.index(start)
    hours = times[idx] + 1 + start
    matrix[idx, start:hours] = 1
matrix

array([[0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.]])

In [27]:
sums = matrix.sum(axis=0)
sums

array([0., 0., 1., 1., 2., 2., 3., 3., 2., 0., 0., 0.])

In [28]:
for i in sums:
    if i > stages:
        answer = "false"
        break
    else:
        answer = "true"
        next
        
    
print(answer)

true
